### ISSUE TITLE
Put Document_DownCont.xlsx in some .md or .adoc file

### ISSUE THREAD

**Issue by amitkrout** [prietyc123/Contacts#2]

**Comment by prietyc123** [comment]
Document_DownCount.xlsx is the documentation of the code. What the text is
doing.

You can download all the file.

Regards,
Priti.

**Comment by amitkrout** [comment]
Addressed over BJN call

Thanks @prietyc123

**Comment by prietyc123** [comment]
Thanks @Amit:)
